/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 16-sep.-2025 21:08:16 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Tb_detalle_pedidos_Tb_MenuPlatos]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Tb_detalle_pedidos] DROP CONSTRAINT [FK_Tb_detalle_pedidos_Tb_MenuPlatos]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Tb_detalle_pedidos_Tb_Pedidos]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Tb_detalle_pedidos] DROP CONSTRAINT [FK_Tb_detalle_pedidos_Tb_Pedidos]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Tb_facturas_Tb_Pedidos]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Tb_facturas] DROP CONSTRAINT [FK_Tb_facturas_Tb_Pedidos]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Tb_inventario_Tb_proveedores]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Tb_inventario] DROP CONSTRAINT [FK_Tb_inventario_Tb_proveedores]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Tb_Pedidos_Tb_clientes ]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Tb_Pedidos] DROP CONSTRAINT [FK_Tb_Pedidos_Tb_clientes ]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Tb_Pedidos_Tb_empleados]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Tb_Pedidos] DROP CONSTRAINT [FK_Tb_Pedidos_Tb_empleados]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Tb_Pedidos_Tb_mesas]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Tb_Pedidos] DROP CONSTRAINT [FK_Tb_Pedidos_Tb_mesas]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Tb_reservas_Tb_clientes ]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Tb_reservas] DROP CONSTRAINT [FK_Tb_reservas_Tb_clientes ]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Tb_reservas_Tb_mesas]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Tb_reservas] DROP CONSTRAINT [FK_Tb_reservas_Tb_mesas]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Tb_clientes ]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Tb_clientes ]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Tb_detalle_pedidos]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Tb_detalle_pedidos]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Tb_empleados]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Tb_empleados]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Tb_facturas]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Tb_facturas]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Tb_inventario]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Tb_inventario]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Tb_MenuPlatos]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Tb_MenuPlatos]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Tb_mesas]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Tb_mesas]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Tb_Pedidos]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Tb_Pedidos]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Tb_proveedores]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Tb_proveedores]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Tb_reservas]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Tb_reservas]
GO

/* Create Tables */

CREATE TABLE [Tb_clientes ]
(
	[idClientes] int NOT NULL,
	[nombre] varchar(100) NOT NULL,
	[apellido] varchar(100) NOT NULL,
	[telefono] varchar(20) NULL,
	[email] varchar(100) NULL,
	[direccion] varchar(200) NULL
)
GO

CREATE TABLE [Tb_detalle_pedidos]
(
	[idDetalle] int NOT NULL,
	[idPedido] int NOT NULL,
	[idPlato] int NOT NULL,
	[cantidad] int NOT NULL,
	[precioUnitario] decimal(10,2) NOT NULL,
	[subTotal] decimal(10,2) NULL,
	[idPedidos] int NULL
)
GO

CREATE TABLE [Tb_empleados]
(
	[idEmpleado] int NOT NULL,
	[nombre] varchar(100) NOT NULL,
	[apellido] varchar(100) NOT NULL,
	[cargo] varchar(50) NOT NULL,
	[telefono] varchar(20) NULL,
	[email] varchar(100) NULL,
	[fecha_contratacion] date NULL,
	[activo] tinyint NOT NULL
)
GO

CREATE TABLE [Tb_facturas]
(
	[idFactura] int NOT NULL,
	[fecha] datetime NOT NULL,
	[idPedido] int NOT NULL,
	[subtotal] decimal(10,2) NOT NULL,
	[impuestos] decimal(10,2) NOT NULL,
	[total] decimal(10,2) NOT NULL,
	[metodo_pago] varchar(50) NULL,
	[idPedidos] int NULL
)
GO

CREATE TABLE [Tb_inventario]
(
	[idProducto] int NOT NULL,
	[nombreProducto] varchar(150) NOT NULL,
	[cantidad] int NOT NULL,
	[precioUnitario] decimal(10,2) NOT NULL,
	[idProveedor] int NULL,
	[minimo_reposicion] int NULL
)
GO

CREATE TABLE [Tb_MenuPlatos]
(
	[idPlato] int NOT NULL,
	[nombrePlato] varchar(150) NOT NULL,
	[descripcion] varchar(255) NULL,
	[precio] decimal(10,2) NOT NULL,
	[categoria] varchar(50) NULL,
	[disponible] tinyint NOT NULL
)
GO

CREATE TABLE [Tb_mesas]
(
	[idMesa] int NOT NULL,
	[numeroMesa] int NOT NULL,
	[capacidad] int NOT NULL,
	[estado] varchar(20) NOT NULL
)
GO

CREATE TABLE [Tb_Pedidos]
(
	[idPedidos] int NOT NULL,
	[fecha] datetime NOT NULL,
	[idEmpleado] int NOT NULL,
	[idMesa] int NOT NULL,
	[estado] varchar(20) NOT NULL,
	[idClientes] int NOT NULL
)
GO

CREATE TABLE [Tb_proveedores]
(
	[idProveedor] int NOT NULL,
	[nombre] varchar(150) NOT NULL,
	[contacto] varchar(100) NULL,
	[telefono] varchar(20) NULL,
	[email] varchar(100) NULL
)
GO

CREATE TABLE [Tb_reservas]
(
	[idReserva] int NOT NULL,
	[idCliente] int NOT NULL,
	[idMesa] int NOT NULL,
	[fecha] date NOT NULL,
	[hora] time NOT NULL,
	[numPersonas] int NOT NULL,
	[estado] varchar(20) NOT NULL,
	[idClientes] int NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Tb_clientes ] 
 ADD CONSTRAINT [PK_Tb_clientes ]
	PRIMARY KEY CLUSTERED ([idClientes] ASC)
GO

ALTER TABLE [Tb_detalle_pedidos] 
 ADD CONSTRAINT [PK_Tb_detalle_pedidos]
	PRIMARY KEY CLUSTERED ([idDetalle] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Tb_detalle_pedidos_Tb_MenuPlatos] 
 ON [Tb_detalle_pedidos] ([idPlato] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Tb_detalle_pedidos_Tb_Pedidos] 
 ON [Tb_detalle_pedidos] ([idPedidos] ASC)
GO

ALTER TABLE [Tb_empleados] 
 ADD CONSTRAINT [PK_Tb_empleados]
	PRIMARY KEY CLUSTERED ([idEmpleado] ASC)
GO

ALTER TABLE [Tb_facturas] 
 ADD CONSTRAINT [PK_Tb_facturas]
	PRIMARY KEY CLUSTERED ([idFactura] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Tb_facturas_Tb_Pedidos] 
 ON [Tb_facturas] ([idPedidos] ASC)
GO

ALTER TABLE [Tb_inventario] 
 ADD CONSTRAINT [PK_Tb_inventario]
	PRIMARY KEY CLUSTERED ([idProducto] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Tb_inventario_Tb_proveedores] 
 ON [Tb_inventario] ([idProveedor] ASC)
GO

ALTER TABLE [Tb_MenuPlatos] 
 ADD CONSTRAINT [PK_Tb_MenuPlatos]
	PRIMARY KEY CLUSTERED ([idPlato] ASC)
GO

ALTER TABLE [Tb_mesas] 
 ADD CONSTRAINT [PK_Tb_mesas]
	PRIMARY KEY CLUSTERED ([idMesa] ASC)
GO

ALTER TABLE [Tb_Pedidos] 
 ADD CONSTRAINT [PK_menuPlatos]
	PRIMARY KEY CLUSTERED ([idPedidos] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Tb_Pedidos_Tb_clientes ] 
 ON [Tb_Pedidos] ([idClientes] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Tb_Pedidos_Tb_empleados] 
 ON [Tb_Pedidos] ([idEmpleado] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Tb_Pedidos_Tb_mesas] 
 ON [Tb_Pedidos] ([idMesa] ASC)
GO

ALTER TABLE [Tb_proveedores] 
 ADD CONSTRAINT [PK_Tb_proveedores]
	PRIMARY KEY CLUSTERED ([idProveedor] ASC)
GO

ALTER TABLE [Tb_reservas] 
 ADD CONSTRAINT [PK_Tb_reservas]
	PRIMARY KEY CLUSTERED ([idReserva] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Tb_reservas_Tb_clientes ] 
 ON [Tb_reservas] ([idClientes] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Tb_reservas_Tb_mesas] 
 ON [Tb_reservas] ([idMesa] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Tb_detalle_pedidos] ADD CONSTRAINT [FK_Tb_detalle_pedidos_Tb_MenuPlatos]
	FOREIGN KEY ([idPlato]) REFERENCES [Tb_MenuPlatos] ([idPlato]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Tb_detalle_pedidos] ADD CONSTRAINT [FK_Tb_detalle_pedidos_Tb_Pedidos]
	FOREIGN KEY ([idPedidos]) REFERENCES [Tb_Pedidos] ([idPedidos]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Tb_facturas] ADD CONSTRAINT [FK_Tb_facturas_Tb_Pedidos]
	FOREIGN KEY ([idPedidos]) REFERENCES [Tb_Pedidos] ([idPedidos]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Tb_inventario] ADD CONSTRAINT [FK_Tb_inventario_Tb_proveedores]
	FOREIGN KEY ([idProveedor]) REFERENCES [Tb_proveedores] ([idProveedor]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Tb_Pedidos] ADD CONSTRAINT [FK_Tb_Pedidos_Tb_clientes ]
	FOREIGN KEY ([idClientes]) REFERENCES [Tb_clientes ] ([idClientes]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Tb_Pedidos] ADD CONSTRAINT [FK_Tb_Pedidos_Tb_empleados]
	FOREIGN KEY ([idEmpleado]) REFERENCES [Tb_empleados] ([idEmpleado]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Tb_Pedidos] ADD CONSTRAINT [FK_Tb_Pedidos_Tb_mesas]
	FOREIGN KEY ([idMesa]) REFERENCES [Tb_mesas] ([idMesa]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Tb_reservas] ADD CONSTRAINT [FK_Tb_reservas_Tb_clientes ]
	FOREIGN KEY ([idClientes]) REFERENCES [Tb_clientes ] ([idClientes]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Tb_reservas] ADD CONSTRAINT [FK_Tb_reservas_Tb_mesas]
	FOREIGN KEY ([idMesa]) REFERENCES [Tb_mesas] ([idMesa]) ON DELETE No Action ON UPDATE No Action
GO
